; Auto-generated. Do not edit!


(cl:in-package action_remote_teleop-msg)


;//! \htmlinclude TurnInPlaceFeedback.msg.html

(cl:defclass <TurnInPlaceFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TurnInPlaceFeedback (<TurnInPlaceFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TurnInPlaceFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TurnInPlaceFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_remote_teleop-msg:<TurnInPlaceFeedback> is deprecated: use action_remote_teleop-msg:TurnInPlaceFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TurnInPlaceFeedback>) ostream)
  "Serializes a message object of type '<TurnInPlaceFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TurnInPlaceFeedback>) istream)
  "Deserializes a message object of type '<TurnInPlaceFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TurnInPlaceFeedback>)))
  "Returns string type for a message object of type '<TurnInPlaceFeedback>"
  "action_remote_teleop/TurnInPlaceFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TurnInPlaceFeedback)))
  "Returns string type for a message object of type 'TurnInPlaceFeedback"
  "action_remote_teleop/TurnInPlaceFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TurnInPlaceFeedback>)))
  "Returns md5sum for a message object of type '<TurnInPlaceFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TurnInPlaceFeedback)))
  "Returns md5sum for a message object of type 'TurnInPlaceFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TurnInPlaceFeedback>)))
  "Returns full string definition for message of type '<TurnInPlaceFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TurnInPlaceFeedback)))
  "Returns full string definition for message of type 'TurnInPlaceFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TurnInPlaceFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TurnInPlaceFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TurnInPlaceFeedback
))
