; Auto-generated. Do not edit!


(cl:in-package action_remote_teleop-msg)


;//! \htmlinclude TurnInPlaceGoal.msg.html

(cl:defclass <TurnInPlaceGoal> (roslisp-msg-protocol:ros-message)
  ((degrees
    :reader degrees
    :initarg :degrees
    :type cl:float
    :initform 0.0))
)

(cl:defclass TurnInPlaceGoal (<TurnInPlaceGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TurnInPlaceGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TurnInPlaceGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_remote_teleop-msg:<TurnInPlaceGoal> is deprecated: use action_remote_teleop-msg:TurnInPlaceGoal instead.")))

(cl:ensure-generic-function 'degrees-val :lambda-list '(m))
(cl:defmethod degrees-val ((m <TurnInPlaceGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_remote_teleop-msg:degrees-val is deprecated.  Use action_remote_teleop-msg:degrees instead.")
  (degrees m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TurnInPlaceGoal>) ostream)
  "Serializes a message object of type '<TurnInPlaceGoal>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'degrees))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TurnInPlaceGoal>) istream)
  "Deserializes a message object of type '<TurnInPlaceGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'degrees) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TurnInPlaceGoal>)))
  "Returns string type for a message object of type '<TurnInPlaceGoal>"
  "action_remote_teleop/TurnInPlaceGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TurnInPlaceGoal)))
  "Returns string type for a message object of type 'TurnInPlaceGoal"
  "action_remote_teleop/TurnInPlaceGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TurnInPlaceGoal>)))
  "Returns md5sum for a message object of type '<TurnInPlaceGoal>"
  "183d8e3d55aba4fbf99109a319f491b0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TurnInPlaceGoal)))
  "Returns md5sum for a message object of type 'TurnInPlaceGoal"
  "183d8e3d55aba4fbf99109a319f491b0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TurnInPlaceGoal>)))
  "Returns full string definition for message of type '<TurnInPlaceGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%float64 degrees~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TurnInPlaceGoal)))
  "Returns full string definition for message of type 'TurnInPlaceGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%float64 degrees~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TurnInPlaceGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TurnInPlaceGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TurnInPlaceGoal
    (cl:cons ':degrees (degrees msg))
))
