; Auto-generated. Do not edit!


(cl:in-package action_remote_teleop-msg)


;//! \htmlinclude TurnInPlaceResult.msg.html

(cl:defclass <TurnInPlaceResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass TurnInPlaceResult (<TurnInPlaceResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TurnInPlaceResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TurnInPlaceResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_remote_teleop-msg:<TurnInPlaceResult> is deprecated: use action_remote_teleop-msg:TurnInPlaceResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <TurnInPlaceResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_remote_teleop-msg:success-val is deprecated.  Use action_remote_teleop-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TurnInPlaceResult>) ostream)
  "Serializes a message object of type '<TurnInPlaceResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TurnInPlaceResult>) istream)
  "Deserializes a message object of type '<TurnInPlaceResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TurnInPlaceResult>)))
  "Returns string type for a message object of type '<TurnInPlaceResult>"
  "action_remote_teleop/TurnInPlaceResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TurnInPlaceResult)))
  "Returns string type for a message object of type 'TurnInPlaceResult"
  "action_remote_teleop/TurnInPlaceResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TurnInPlaceResult>)))
  "Returns md5sum for a message object of type '<TurnInPlaceResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TurnInPlaceResult)))
  "Returns md5sum for a message object of type 'TurnInPlaceResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TurnInPlaceResult>)))
  "Returns full string definition for message of type '<TurnInPlaceResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TurnInPlaceResult)))
  "Returns full string definition for message of type 'TurnInPlaceResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TurnInPlaceResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TurnInPlaceResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TurnInPlaceResult
    (cl:cons ':success (success msg))
))
