// Generated by gencpp from file action_remote_teleop/CountUntilGoal.msg
// DO NOT EDIT!


#ifndef ACTION_REMOTE_TELEOP_MESSAGE_COUNTUNTILGOAL_H
#define ACTION_REMOTE_TELEOP_MESSAGE_COUNTUNTILGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_remote_teleop
{
template <class ContainerAllocator>
struct CountUntilGoal_
{
  typedef CountUntilGoal_<ContainerAllocator> Type;

  CountUntilGoal_()
    : max_number(0)
    , wait_duration(0.0)  {
    }
  CountUntilGoal_(const ContainerAllocator& _alloc)
    : max_number(0)
    , wait_duration(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _max_number_type;
  _max_number_type max_number;

   typedef double _wait_duration_type;
  _wait_duration_type wait_duration;





  typedef boost::shared_ptr< ::action_remote_teleop::CountUntilGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_remote_teleop::CountUntilGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CountUntilGoal_

typedef ::action_remote_teleop::CountUntilGoal_<std::allocator<void> > CountUntilGoal;

typedef boost::shared_ptr< ::action_remote_teleop::CountUntilGoal > CountUntilGoalPtr;
typedef boost::shared_ptr< ::action_remote_teleop::CountUntilGoal const> CountUntilGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_remote_teleop::CountUntilGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_remote_teleop::CountUntilGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_remote_teleop::CountUntilGoal_<ContainerAllocator1> & lhs, const ::action_remote_teleop::CountUntilGoal_<ContainerAllocator2> & rhs)
{
  return lhs.max_number == rhs.max_number &&
    lhs.wait_duration == rhs.wait_duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_remote_teleop::CountUntilGoal_<ContainerAllocator1> & lhs, const ::action_remote_teleop::CountUntilGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_remote_teleop

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_remote_teleop::CountUntilGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_remote_teleop::CountUntilGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_remote_teleop::CountUntilGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_remote_teleop::CountUntilGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_remote_teleop::CountUntilGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_remote_teleop::CountUntilGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_remote_teleop::CountUntilGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca8c86ed62b42e478aaac2e19c943016";
  }

  static const char* value(const ::action_remote_teleop::CountUntilGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca8c86ed62b42e47ULL;
  static const uint64_t static_value2 = 0x8aaac2e19c943016ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_remote_teleop::CountUntilGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_remote_teleop/CountUntilGoal";
  }

  static const char* value(const ::action_remote_teleop::CountUntilGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_remote_teleop::CountUntilGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal         \n"
"int64 max_number\n"
"float64 wait_duration\n"
;
  }

  static const char* value(const ::action_remote_teleop::CountUntilGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_remote_teleop::CountUntilGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.max_number);
      stream.next(m.wait_duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CountUntilGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_remote_teleop::CountUntilGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_remote_teleop::CountUntilGoal_<ContainerAllocator>& v)
  {
    s << indent << "max_number: ";
    Printer<int64_t>::stream(s, indent + "  ", v.max_number);
    s << indent << "wait_duration: ";
    Printer<double>::stream(s, indent + "  ", v.wait_duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_REMOTE_TELEOP_MESSAGE_COUNTUNTILGOAL_H
