// Generated by gencpp from file action_remote_teleop/TurnInPlaceGoal.msg
// DO NOT EDIT!


#ifndef ACTION_REMOTE_TELEOP_MESSAGE_TURNINPLACEGOAL_H
#define ACTION_REMOTE_TELEOP_MESSAGE_TURNINPLACEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_remote_teleop
{
template <class ContainerAllocator>
struct TurnInPlaceGoal_
{
  typedef TurnInPlaceGoal_<ContainerAllocator> Type;

  TurnInPlaceGoal_()
    : degrees(0.0)  {
    }
  TurnInPlaceGoal_(const ContainerAllocator& _alloc)
    : degrees(0.0)  {
  (void)_alloc;
    }



   typedef double _degrees_type;
  _degrees_type degrees;





  typedef boost::shared_ptr< ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator> const> ConstPtr;

}; // struct TurnInPlaceGoal_

typedef ::action_remote_teleop::TurnInPlaceGoal_<std::allocator<void> > TurnInPlaceGoal;

typedef boost::shared_ptr< ::action_remote_teleop::TurnInPlaceGoal > TurnInPlaceGoalPtr;
typedef boost::shared_ptr< ::action_remote_teleop::TurnInPlaceGoal const> TurnInPlaceGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator1> & lhs, const ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator2> & rhs)
{
  return lhs.degrees == rhs.degrees;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator1> & lhs, const ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_remote_teleop

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "183d8e3d55aba4fbf99109a319f491b0";
  }

  static const char* value(const ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x183d8e3d55aba4fbULL;
  static const uint64_t static_value2 = 0xf99109a319f491b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_remote_teleop/TurnInPlaceGoal";
  }

  static const char* value(const ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal\n"
"float64 degrees\n"
;
  }

  static const char* value(const ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.degrees);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurnInPlaceGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_remote_teleop::TurnInPlaceGoal_<ContainerAllocator>& v)
  {
    s << indent << "degrees: ";
    Printer<double>::stream(s, indent + "  ", v.degrees);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_REMOTE_TELEOP_MESSAGE_TURNINPLACEGOAL_H
