// Generated by gencpp from file action_remote_teleop/TurnInPlaceResult.msg
// DO NOT EDIT!


#ifndef ACTION_REMOTE_TELEOP_MESSAGE_TURNINPLACERESULT_H
#define ACTION_REMOTE_TELEOP_MESSAGE_TURNINPLACERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_remote_teleop
{
template <class ContainerAllocator>
struct TurnInPlaceResult_
{
  typedef TurnInPlaceResult_<ContainerAllocator> Type;

  TurnInPlaceResult_()
    : success(false)  {
    }
  TurnInPlaceResult_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator> const> ConstPtr;

}; // struct TurnInPlaceResult_

typedef ::action_remote_teleop::TurnInPlaceResult_<std::allocator<void> > TurnInPlaceResult;

typedef boost::shared_ptr< ::action_remote_teleop::TurnInPlaceResult > TurnInPlaceResultPtr;
typedef boost::shared_ptr< ::action_remote_teleop::TurnInPlaceResult const> TurnInPlaceResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator1> & lhs, const ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator1> & lhs, const ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_remote_teleop

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_remote_teleop/TurnInPlaceResult";
  }

  static const char* value(const ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"bool success\n"
;
  }

  static const char* value(const ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurnInPlaceResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_remote_teleop::TurnInPlaceResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_REMOTE_TELEOP_MESSAGE_TURNINPLACERESULT_H
