// Generated by gencpp from file action_remote_teleop/TurnInPlaceFeedback.msg
// DO NOT EDIT!


#ifndef ACTION_REMOTE_TELEOP_MESSAGE_TURNINPLACEFEEDBACK_H
#define ACTION_REMOTE_TELEOP_MESSAGE_TURNINPLACEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_remote_teleop
{
template <class ContainerAllocator>
struct TurnInPlaceFeedback_
{
  typedef TurnInPlaceFeedback_<ContainerAllocator> Type;

  TurnInPlaceFeedback_()
    {
    }
  TurnInPlaceFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct TurnInPlaceFeedback_

typedef ::action_remote_teleop::TurnInPlaceFeedback_<std::allocator<void> > TurnInPlaceFeedback;

typedef boost::shared_ptr< ::action_remote_teleop::TurnInPlaceFeedback > TurnInPlaceFeedbackPtr;
typedef boost::shared_ptr< ::action_remote_teleop::TurnInPlaceFeedback const> TurnInPlaceFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace action_remote_teleop

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_remote_teleop/TurnInPlaceFeedback";
  }

  static const char* value(const ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"\n"
;
  }

  static const char* value(const ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurnInPlaceFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::action_remote_teleop::TurnInPlaceFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_REMOTE_TELEOP_MESSAGE_TURNINPLACEFEEDBACK_H
